DB_URL=postgresql://root:password@localhost:5432/backend?sslmode=disable

postgres:
	docker run --name postgres -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -d postgres

createdb:
	docker exec -it postgres createdb --username=root --owner=root backend

dropdb:
	docker exec -it postgres dropdb backend

migrateup:
	migrate -path cmd/migration -database "postgresql://root:password@localhost:5432/backend?sslmode=disable" -verbose up

migrateup1:
	migrate -path cmd/migration -database "postgresql://root:password@localhost:5432/backend?sslmode=disable" -verbose up 1

migratedown:
	migrate -path cmd/migration -database "postgresql://root:password@localhost:5432/backend?sslmode=disable" -verbose down

migratedown1:
	migrate -path cmd/migration -database "postgresql://root:password@localhost:5432/backend?sslmode=disable" -verbose down 1

new_migration:
	migrate create -ext sql -dir cmd/migration -seq $(name)

sqlc:
	sqlc generate

server:
	air

evans:
	evans --host localhost --port 9090 -r repl

redis:
	docker run --name redis -p 6379:6379 -d redis:7-alpine

.PHONY: network postgres createdb dropdb migrateup migratedown migrateup1 migratedown1 new_migration db_docs db_schema sqlc test server mock proto evans redis